import Head from "next/head";
import Partners from "../components/Home/Partners";
import Contact from "../components/Home/Contact";
import Showcase from "../components/Home/Showcase";
import Programs from "../components/Home/Programs";
import News from "../components/Home/News";
import Informationcard from "../components/Informationcard";
export default function Home() {
  return (
    <>
      <Head>
        <title>Amity Tashkent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Showcase />
      <Programs />
      <News />
      <Informationcard />
      <Partners />
      <Contact />
    </>
  );
}
