import Head from "next/head";
import Partners from "../components/Home/Partners";
import Contact from "../components/Home/Contact";
import Showcase from "../components/Home/Showcase";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Amity Tashkent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Showcase />
      <div className="container">
        <h1>lorem</h1>
        <h1>lorem</h1>
        <h1>lorem</h1>
      </div>
      <Partners />
      <Contact />
    </div>
  );
}
